name: CI-CD

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}


      - name: Build and push Docker images
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:
            dnpimentel/rotten-potatoes:latest
            dnpimentel/rotten-potatoes:v${{ github.run_number }}
